//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoticLight.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sms_DataDictionary> Sms_DataDictionary { get; set; }
        public virtual DbSet<Sms_Setting> Sms_Setting { get; set; }
        public virtual DbSet<Sys_Action> Sys_Action { get; set; }
        public virtual DbSet<Sys_Department> Sys_Department { get; set; }
        public virtual DbSet<Sys_GridView> Sys_GridView { get; set; }
        public virtual DbSet<Sys_Log> Sys_Log { get; set; }
        public virtual DbSet<Sys_Menu> Sys_Menu { get; set; }
        public virtual DbSet<Sys_Relation> Sys_Relation { get; set; }
        public virtual DbSet<Sys_Role> Sys_Role { get; set; }
        public virtual DbSet<Sys_User> Sys_User { get; set; }
        public virtual DbSet<Sys_UserToken> Sys_UserToken { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<YqGSM> YqGSM { get; set; }
        public virtual DbSet<YqGSMFeedBack> YqGSMFeedBack { get; set; }
        public virtual DbSet<YqLocation> YqLocation { get; set; }
        public virtual DbSet<YqNPSA> YqNPSA { get; set; }
        public virtual DbSet<YqNPSAData> YqNPSAData { get; set; }
        public virtual DbSet<YqNPSAInputData> YqNPSAInputData { get; set; }
        public virtual DbSet<YqPN> YqPN { get; set; }
        public virtual DbSet<YqPnLocation> YqPnLocation { get; set; }
        public virtual DbSet<YqPnProject> YqPnProject { get; set; }
        public virtual DbSet<YqPnQty> YqPnQty { get; set; }
        public virtual DbSet<YqProject> YqProject { get; set; }
        public virtual DbSet<YqSBBType> YqSBBType { get; set; }
        public virtual DbSet<YqVendor> YqVendor { get; set; }
        public virtual DbSet<YqWeek> YqWeek { get; set; }
        public virtual DbSet<YqViewNPSAData> YqViewNPSAData { get; set; }
        public virtual DbSet<YqViewNPSAInputData> YqViewNPSAInputData { get; set; }
        public virtual DbSet<YqViewPN> YqViewPN { get; set; }
    }
}
