//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoticLight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Department
    {
        public string Id { get; set; }
        public string DeptName { get; set; }
        public string AdID { get; set; }
        public string ParentId { get; set; }
        public bool IsDelete { get; set; }
        public string code { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string updator { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<int> Int01 { get; set; }
        public Nullable<int> Int02 { get; set; }
        public Nullable<int> Int03 { get; set; }
        public Nullable<int> Int04 { get; set; }
        public Nullable<int> Int05 { get; set; }
        public string str01 { get; set; }
        public string str02 { get; set; }
        public string str03 { get; set; }
        public string str04 { get; set; }
        public string str05 { get; set; }
        public Nullable<double> db01 { get; set; }
        public Nullable<double> db02 { get; set; }
        public Nullable<double> db03 { get; set; }
        public Nullable<double> db04 { get; set; }
        public Nullable<double> db05 { get; set; }
    }
}
