//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoticLight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Menu
    {
        public string Id { get; set; }
        public string ParentId { get; set; }
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> SortCode { get; set; }
        public string Describe { get; set; }
        public string Status { get; set; }
        public string MenuIcon { get; set; }
        public string MenuHref { get; set; }
        public bool IsLeaf { get; set; }
        public bool ShowCheck { get; set; }
        public bool IsExpand { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreatTime { get; set; }
        public string Creator { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public string Modifier { get; set; }
    }
}
