//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoticLight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Relation
    {
        public string Id { get; set; }
        public string RelationName { get; set; }
        public string RelationOne { get; set; }
        public string RelationTwo { get; set; }
        public string Modifier { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreatTime { get; set; }
        public string Creator { get; set; }
        public System.DateTime ModifyTime { get; set; }
    }
}
