//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoticLight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Log
    {
        public string Id { get; set; }
        public Nullable<int> CategoryType { get; set; }
        public Nullable<int> OperateTypeId { get; set; }
        public string OperateType { get; set; }
        public string SourceObjectId { get; set; }
        public string SourceContentJson { get; set; }
        public Nullable<System.DateTime> OperateTime { get; set; }
        public string OperateUserId { get; set; }
        public string OperateAccount { get; set; }
        public string MenuId { get; set; }
        public string MenuName { get; set; }
        public string AccessURL { get; set; }
        public string IPAddress { get; set; }
        public string Host { get; set; }
        public string Browser { get; set; }
        public string ExecuteResult { get; set; }
        public string ExecuteResultJson { get; set; }
        public string Description { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public string Modifier { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreatTime { get; set; }
        public string Creator { get; set; }
    }
}
