//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoticLight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_UserToken
    {
        public string Token { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Modifier { get; set; }
    }
}
