//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoticLight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Action
    {
        public string Id { get; set; }
        public string MenuId { get; set; }
        public string ActionCode { get; set; }
        public string ActionName { get; set; }
        public string Describe { get; set; }
        public string Status { get; set; }
        public string ActionIcon { get; set; }
        public string ActionHref { get; set; }
        public string Modifier { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreatTime { get; set; }
        public string Creator { get; set; }
        public System.DateTime ModifyTime { get; set; }
    }
}
