//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoticLight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YqGSMFeedBack
    {
        public string Id { get; set; }
        public string GSM { get; set; }
        public string PN { get; set; }
        public string Location { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> weekInt { get; set; }
        public Nullable<System.DateTime> FeekBackTime { get; set; }
    }
}
