//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoticLight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YqViewNPSAData
    {
        public string Id { get; set; }
        public Nullable<int> WeekInt { get; set; }
        public string PN { get; set; }
        public string Desp { get; set; }
        public string Project { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> API { get; set; }
        public string NPSA { get; set; }
    }
}
